# Generated by Django 5.0.1 on 2024-02-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chargerequest_requested_credit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit')], default='Withdraw', max_length=10),
        ),
    ]
