# Generated by Django 5.0.1 on 2024-02-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_requested_credit_amount_chargerequest_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditrequest',
            old_name='requested_credit_amount',
            new_name='amount',
        ),
    ]
