# Generated by Django 5.0.1 on 2024-02-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_requested_credit_amount_creditrequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargerequest',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
