# Generated by Django 5.0.1 on 2024-02-05 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_chargerequest_phone_number_delete_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
