# Generated by Django 5.0.1 on 2024-02-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaction_transaction_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargerequest',
            name='status',
        ),
    ]
