# Generated by Django 5.0.1 on 2024-02-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_chargerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
